import type { InvocationStatus, Project } from "../types";
import type {
  Requirement,
  RequirementAdvancement,
  RequirementAdvancementStatus,
  RequirementDetail,
  RequirementLane
} from "./types";

export interface RequirementAdvancementConfig {
  entrancePolicyId: string;
  autoPollEnabled: boolean;
  pollIntervalMs: number;
}

export interface RequirementInvocationObservation {
  invocationId: string;
  runId: string;
  status: InvocationStatus;
  observedAt: string;
  error?: string;
  /** Explicit terminal Run family handoff validated by the board before replacing an Invocation. */
  replacesInvocationId?: string;
}

export type RequirementAdvancementPollAction =
  | { kind: "launch"; requirementId: string; config: RequirementAdvancementConfig }
  | { kind: "observe"; requirementId: string; invocationId: string; config: RequirementAdvancementConfig };

const ACTIVE_STATUSES = new Set<RequirementAdvancementStatus>([
  "dispatching",
  "queued",
  "running",
  "awaiting-human-decision"
]);

const IDEMPOTENCY_COLLISION = /idempotency key .* already bound to another workflow Invocation/i;

function advancementNonce(): string {
  return globalThis.crypto?.randomUUID?.()
    ?? `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

function advancementKey(requirement: RequirementDetail, cycle: number): string {
  // Requirement ids are generated by a browser-local board. Different browser profiles can
  // therefore both own `req-local-1`; project/id/cycle alone is not globally idempotent at the
  // shared daemon boundary. Persist a random nonce in the advancement record so retries still
  // reuse one key while independent boards can never bind each other's Invocation.
  return `requirement:${requirement.projectId}:${requirement.id}:advance:${cycle}:${advancementNonce()}`;
}

function record(value: unknown): Record<string, unknown> | undefined {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? value as Record<string, unknown>
    : undefined;
}

function positivePollInterval(value: unknown): number {
  return typeof value === "number" && Number.isInteger(value) && value >= 5_000 && value <= 300_000
    ? value
    : 15_000;
}

/** Project descriptor config is the only binding between a project and its advancement policy. */
export function requirementAdvancementConfig(project: Project | undefined): RequirementAdvancementConfig | undefined {
  const config = record(project?.connector.config.requirementAdvancement);
  const entrancePolicyId = typeof config?.entrancePolicyId === "string" ? config.entrancePolicyId.trim() : "";
  if (!entrancePolicyId) return undefined;
  const polling = record(config!.polling);
  return {
    entrancePolicyId,
    autoPollEnabled: polling?.enabled === true,
    pollIntervalMs: positivePollInterval(polling?.intervalMs)
  };
}

export function isActiveRequirementAdvancement(advancement: RequirementAdvancement | undefined): boolean {
  return Boolean(advancement && ACTIVE_STATUSES.has(advancement.status));
}

/**
 * `owner` is the human/product ownership placeholder. Once a real advancement
 * cycle has been reserved, showing "待分配" is misleading because the work is
 * already owned by the governed Agent workflow even before a member node runs.
 */
export function requirementOwnerLabel(requirement: Pick<Requirement, "owner" | "advancement">): string {
  return requirement.advancement ? "Agent 团队" : requirement.owner;
}

export function advancementLane(status: RequirementAdvancementStatus, current: RequirementLane): RequirementLane {
  if (status === "queued" || status === "dispatching") return "queued";
  if (status === "awaiting-human-decision") return "confirmation";
  if (status === "running" || status === "completed") return "running";
  // Blocked / failed / cancelled are exception overlays, not lifecycle lanes.
  // Once a paused Run terminates it must leave the confirmation lane; otherwise
  // the card keeps looking actionable even though there is no pending decision.
  if (current === "confirmation") return "running";
  return current;
}

export function reserveAdvancement(
  requirement: RequirementDetail,
  config: RequirementAdvancementConfig,
  trigger: RequirementAdvancement["trigger"],
  at: string
): RequirementAdvancement {
  const current = requirement.advancement;
  // A lost HTTP response must retry the same cycle/key. This is the critical
  // bridge between today's button and a future polling scanner.
  if (current?.status === "dispatching" && !current.invocationId) {
    return { ...current, trigger, updatedAt: at, nextCheckAt: at, error: undefined };
  }
  if (current?.status === "failed" && !current.invocationId) {
    // A lost HTTP response must reuse its persisted key. A proven daemon-side collision is the
    // one exception: that key belongs to another board, so retrying it can never succeed.
    const idempotencyKey = current.error && IDEMPOTENCY_COLLISION.test(current.error)
      ? advancementKey(requirement, current.cycle)
      : current.idempotencyKey;
    return { ...current, idempotencyKey, trigger, status: "dispatching", updatedAt: at, nextCheckAt: at, error: undefined };
  }
  if (isActiveRequirementAdvancement(current)) {
    throw new Error(`需求已有进行中的推进任务：${current?.invocationId ?? current?.idempotencyKey}`);
  }
  if (current?.invocationId && current.status !== "failed" && current.status !== "blocked") {
    throw new Error("这轮推进已经产生 Run；请先在运行卷宗处理结果，再决定是否重新推进");
  }
  if (requirement.lane === "clarify") throw new Error("需求仍在待澄清；请先补齐关键信息并迁移回收件箱或已规划");
  if (requirement.lane === "acceptance" || requirement.lane === "merging" || requirement.lane === "done") {
    const label = requirement.lane === "acceptance" ? "待验收" : requirement.lane === "merging" ? "待合入" : "已完成";
    throw new Error(`需求已经位于「${label}」，不能重新开始推进`);
  }
  if (requirement.exception === "cancelled") throw new Error("已取消的需求不能开始推进");
  if (requirement.acceptanceCriteria.length === 0) throw new Error("缺少验收标准；请先补齐可观察的验收标准");
  const cycle = (current?.cycle ?? 0) + 1;
  return {
    schemaVersion: 1,
    cycle,
    trigger,
    status: "dispatching",
    entrancePolicyId: config.entrancePolicyId,
    idempotencyKey: advancementKey(requirement, cycle),
    startedAt: at,
    updatedAt: at,
    nextCheckAt: at
  };
}

export function observeAdvancement(
  advancement: RequirementAdvancement,
  observation: RequirementInvocationObservation,
  pollIntervalMs: number
): RequirementAdvancement {
  if (advancement.invocationId && advancement.invocationId !== observation.invocationId) {
    const replacesTerminalInvocation = observation.replacesInvocationId === advancement.invocationId
      && (advancement.status === "blocked" || advancement.status === "failed");
    if (!replacesTerminalInvocation) throw new Error("推进观察结果不属于当前需求的 Invocation");
  }
  // SSE reconnects and overlapping polls may deliver an older snapshot after a
  // newer one. The local board projection must never regress from running back to
  // awaiting-human-decision (or from terminal to active) because of that race.
  if (advancement.invocationId
    && advancement.invocationId === observation.invocationId
    && new Date(observation.observedAt).getTime() < new Date(advancement.updatedAt).getTime()) {
    return advancement;
  }
  const status = observation.status;
  const terminal = status === "completed" || status === "blocked" || status === "failed" || status === "cancelled";
  return {
    ...advancement,
    status,
    invocationId: observation.invocationId,
    runId: observation.runId,
    updatedAt: observation.observedAt,
    ...(terminal ? { nextCheckAt: undefined } : {
      nextCheckAt: new Date(new Date(observation.observedAt).getTime() + pollIntervalMs).toISOString()
    }),
    ...(observation.error ? { error: observation.error } : { error: undefined })
  };
}

/** Pure selection function for the future interval worker; it performs no dispatch or writes. */
export function dueRequirementAdvancements(requirements: Requirement[], now: string): Requirement[] {
  const timestamp = new Date(now).getTime();
  return requirements.filter((requirement) => {
    const advancement = requirement.advancement;
    if (!advancement || !isActiveRequirementAdvancement(advancement) || !advancement.nextCheckAt) return false;
    return new Date(advancement.nextCheckAt).getTime() <= timestamp;
  });
}

/**
 * Side-effect-free polling plan. A future timer/queue may execute these actions, but it must call
 * the same reserve/dispatch/sync methods as the human button so automatic and manual starts cannot diverge.
 */
export function planRequirementAdvancementPoll(
  requirements: RequirementDetail[],
  configForProject: (projectId: string) => RequirementAdvancementConfig | undefined,
  now: string
): RequirementAdvancementPollAction[] {
  const timestamp = new Date(now).getTime();
  const actions: RequirementAdvancementPollAction[] = [];
  for (const requirement of requirements) {
    const config = configForProject(requirement.projectId);
    if (!config?.autoPollEnabled || requirement.archivedAt || requirement.exception === "cancelled") continue;
    const advancement = requirement.advancement;
    const due = !advancement?.nextCheckAt || new Date(advancement.nextCheckAt).getTime() <= timestamp;
    if (advancement?.invocationId && isActiveRequirementAdvancement(advancement) && due) {
      actions.push({ kind: "observe", requirementId: requirement.id, invocationId: advancement.invocationId, config });
      continue;
    }
    const retryable = !advancement || (!advancement.invocationId && advancement.status === "failed")
      || (!advancement.invocationId && advancement.status === "dispatching" && due);
    const eligibleLane = requirement.lane === "inbox" || requirement.lane === "planned" || requirement.lane === "queued";
    if (retryable && eligibleLane && requirement.acceptanceCriteria.length > 0) {
      actions.push({ kind: "launch", requirementId: requirement.id, config });
    }
  }
  return actions;
}
